export const PRODUCT_TO_EDIT = "PRODUCT_TO_EDIT";

export const UPDATE_PRODUCT_INIT = "UPDATE_PRODUCT_INIT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const FETCH_USER_PRODUCTS_INIT = "FETCH_USER_PRODUCTS_INIT";
export const FETCH_USER_PRODUCTS_SUCCESS = "FETCH_USER_PRODUCTS_SUCCESS";
export const FETCH_USER_PRODUCTS_FAIL = "FETCH_USER_PRODUCTS_FAIL";

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
//?shop

export const FETCH_CART_ITEMS_INIT = "FETCH_CART_ITEMS_INIT";
export const FETCH_CART_ITEMS_SUCCESS = "FETCH_CART_ITEMS_SUCCESS";
export const FETCH_CART_ITEMS_FAIL = "FETCH_CART_ITEMS_FAIL";
export const FETCH_CART_ITEMS_EMPTY = "FETCH_CART_ITEMS_EMPTY";

//? order
export const CREATE_ORDER_INIT = "CREATE_ORDER_INIT";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const FETCH_ORDER_INIT = "FETCH_ORDER_INIT";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const SET_CART_ITEMS_COUNT = "SET_CART_ITEMS_COUNT";
